// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujhgvcdrbjsluynsyygm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaGd2Y2RyYmpzbHV5bnN5eWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDM0NDAsImV4cCI6MjA3MTExOTQ0MH0.GgNlOYkh6vPkxuK2aTRuo5tYlPJBGWdMBtmKewEhdI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});